name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby: [2.4.10, 2.5.9, 2.6.10, 2.7.8, 3.0, 3.1, 3.2, 3.3]

    env:
      BUNDLE_PATH: .bundle

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v1
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: dependencies-${{ hashFiles('Gemfile.lock') }}
          restore-keys: dependencies-

      - name: Install dependencies
        run: |
          bundle install --jobs 3 --retry 3

      - name: Run tests
        run: RUBYOPT="-E UTF-8" bundle exec rake
